spring.application.name=myflix
spring.mongodb.uri=mongodb://localhost:27017/filmes
logging.level.org.apache.kafka=ERROR
logging.level.org.apache.kafka.common.config=ERROR
logging.level.org.apache.kafka.clients=ERROR
logging.level.org.springframework.kafka=INFO